name: Custom Tagging Workflow

on:
  workflow_dispatch:
    inputs:
      custom_tag:
        description: 'Custom Tag (leave empty to auto-increment from the latest tag)'
        required: false
        default: ''

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Configure Git
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"

      - name: Determine new tag
        id: newtag
        env:
          CUSTOM_TAG: ${{ github.event.inputs.custom_tag }}
        run: |
          if [[ -z "$CUSTOM_TAG" ]]; then
            # Fetch tags
            git fetch --tags

            # Get the latest tag
            LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
            
            if [[ -z "$LAST_TAG" ]]; then
              # Default tag if there are no tags
              echo "No existing tags. Starting with v0.0.1"
              NEW_TAG="v0.0.1"
            else
              echo "Latest tag is $LAST_TAG"
              # Increment the latest tag
              NEW_TAG=$(echo $LAST_TAG | awk -F. -v OFS=. '{$NF++; print}')
            fi
          else
            echo "Using custom tag: $CUSTOM_TAG"
            NEW_TAG=$CUSTOM_TAG
          fi
          echo "New tag: $NEW_TAG"
          echo "::set-output name=NEW_TAG::$NEW_TAG"

      - name: Create and Push Tag
        env:
          TEMP_TOKEN2: ${{ secrets.TEMP_TOKEN2 }}
        run: |
          NEW_TAG=${{ steps.newtag.outputs.NEW_TAG }}
          git tag -a $NEW_TAG -m "Version $NEW_TAG"
          git push https://${TEMP_TOKEN2}@github.com/chamathns/sample-python-project.git $NEW_TAG
